title: Juan Quiroz
theme: jekyll-theme-cayman
google_scholar_url: https://scholar.google.com/citations?user=X2hoQqwAAAAJ&hl=en
linkedin_url: https://www.linkedin.com/in/juancquiroz/
cv_url: /assets/juan_quiroz_cv.pdf
